services:
  website:
    container_name: website
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - cloudflared

    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token ${TOKEN}
    environment:
      - TZ=US/Eastern
      - TOKEN=${TOKEN}
    networks:
      - cloudflared
    depends_on:
      - website

networks:
  cloudflared:
    name: cloudflared
    driver: bridge
