services:
  eva:
    container_name: eva
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dokploy-network
    expose:
      - "3000"
    restart: always

networks:
  dokploy-network:
    name: dokploy-network
    external: true
